project:
  type: website
  output-dir: docs

website:
  title: "James Forster III Website"
  navbar:
    left:
      - href: index.qmd
        text: Welcome to My Website!!!
      - about.qmd
      - Labs.qmd
      - Project.qmd
      - Presentation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

